name: aivantu_frontend
description: AiVantu production frontend (single file example)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  dio: ^5.2.1
  provider: ^6.0.5
  image_picker: ^0.8.7+5
  file_picker: ^5.2.2
  path_provider: ^2.0.15
  video_player: ^2.6.0
  audioplayers: ^2.1.1
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
