services:
  # Backend Service
  - type: web
    name: ai-video-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10

  # Frontend Service (Flutter Web)
  - type: web
    name: ai-video-frontend
    env: static
    buildCommand: flutter build web
    staticPublishPath: build/web
    plan: free
